[package]
name = "ninja-vs-pirates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_rapier3d = "0.22.0"
# bevy-inspector-egui = "0.19"
bevy_hanabi = "0.7"